version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.1
jobs:
  build:
    docker:
      - image: bnxdev/bnx-firmware-builder
    resource_class: 2xlarge
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "26:2e:1f:27:d4:59:d7:27:23:0c:05:7c:cf:0e:d3:8b"
      - run: bash .circleci/build.sh $CIRCLE_TAG $CIRCLE_BUILD_NUM workspace $BNX_DEVICE_SECRET $BNX_FIRMWARE_SECRET
      - persist_to_workspace:
          root: workspace
          paths:
            - '*'
  upload:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/setup
      - run: bash /tmp/workspace/deploy.sh /tmp/workspace
workflows:
  version: 2
  bnxfw:
    jobs:
      - build:
          name: BuildFw
          filters:
            tags:
              only:
                - /bnx\/release\/.*/
            branches:
              ignore:
                - /.*/
      - upload:
          name: UploadFw
          requires:
            - BuildFw
          filters:
            tags:
              only:
                - /bnx\/release\/.*/
            branches:
              ignore:
                - /.*/
